name: Build and Deploy Project

on:
  push:
    branches: [ main ]
  # No longer building on pull_request to avoid deploying un-merged code
  # pull_request:
  #   branches: [ main ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and Push Compiled JS
        # This step only runs on pushes to the main branch, not on pull requests.
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          # Configure Git with the bot's identity
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Force-add the compiled JavaScript file (update path if necessary)
          git add -f build/dist/js/productionExecutable/shashwathkamath.github.io.js
          
          # Commit the file if there are any changes
          # The '|| exit 0' part prevents the workflow from failing if there's nothing to commit
          git commit -m "CI: Build and deploy latest JS" || exit 0
          
          # Push the changes back to the main branch
          git push